# Data Manipulation and Analysis with Pandas:

Data manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides a wide range of functions for data manipulation and analysis, making it easier to clean, transform, and extract insights from data. In this lesson, we will cover various data manipulation and analysis techniques using Pandas.

In [ ]:
import pandas as pd
df = pd.read_csv('sales1_data.csv')

In [ ]:
df.head()

         Date   Product  Sales Region
0  2023-01-01  Product3  738.0   West
1  2023-01-02  Product2  868.0  North
2  2023-01-03  Product2  554.0   West
3  2023-01-04  Product1  618.0  South
4  2023-01-05  Product3  501.0   East

In [ ]:
# ## Handling Missing Values
df.isnull().any()

Date       False
Product    False
Sales       True
Region     False
dtype: bool

In [ ]:
df.isnull().sum()

Date       0
Product    0
Sales      6
Region     0
dtype: int64

### filling missing values with the mean of the column

In [ ]:
df['Sales'] = df['Sales'].fillna(df['Sales'].mean())

In [ ]:
df.isnull().sum()

Date       0
Product    0
Sales      0
Region     0
dtype: int64

### Renaming Columns:

In [ ]:
df = df.rename(columns={'Date':'Sales Date'})
df

    Sales Date   Product  Sales Region
0   2023-01-01  Product3  738.0   West
1   2023-01-02  Product2  868.0  North
2   2023-01-03  Product2  554.0   West
3   2023-01-04  Product1  618.0  South
4   2023-01-05  Product3  501.0   East
5   2023-01-06  Product1  554.0   West
6   2023-01-07  Product3  339.0  South
7   2023-01-08  Product3  280.0  South
8   2023-01-09  Product2  806.0  North
9   2023-01-10  Product2  816.0  South
10  2023-01-11  Product3  469.0   West
11  2023-01-12  Product3  554.0   East
12  2023-01-13  Product3  554.0   East
13  2023-01-14  Product3  676.0   East
14  2023-01-15  Product1  183.0  South
15  2023-01-16  Product1  424.0  South
16  2023-01-17  Product1  554.0  South
17  2023-01-18  Product1  554.0  South
18  2023-01-19  Product2  124.0  North
19  2023-01-20  Product3  732.0   West
20  2023-01-21  Product2  554.0   West
21  2023-01-22  Product3  296.0   West
22  2023-01-23  Product2  737.0   West
23  2023-01-24  Product3  531.0   East
24  2023-01-25  Product2  834.0  North

### Change datatypes:

In [ ]:
df['Value_new'] = df['Sales'].astype(int)
df

    Sales Date   Product  Sales Region  Value_new
0   2023-01-01  Product3  738.0   West        738
1   2023-01-02  Product2  868.0  North        868
2   2023-01-03  Product2  554.0   West        554
3   2023-01-04  Product1  618.0  South        618
4   2023-01-05  Product3  501.0   East        501
5   2023-01-06  Product1  554.0   West        554
6   2023-01-07  Product3  339.0  South        339
7   2023-01-08  Product3  280.0  South        280
8   2023-01-09  Product2  806.0  North        806
9   2023-01-10  Product2  816.0  South        816
10  2023-01-11  Product3  469.0   West        469
11  2023-01-12  Product3  554.0   East        554
12  2023-01-13  Product3  554.0   East        554
13  2023-01-14  Product3  676.0   East        676
14  2023-01-15  Product1  183.0  South        183
15  2023-01-16  Product1  424.0  South        424
16  2023-01-17  Product1  554.0  South        554
17  2023-01-18  Product1  554.0  South        554
18  2023-01-19  Product2  124.0  North        124
19  2023-01-20  Product3  732.0   West        732
20  2023-01-21  Product2  554.0   West        554
21  2023-01-22  Product3  296.0   West        296
22  2023-01-23  Product2  737.0   West        737
23  2023-01-24  Product3  531.0   East        531
24  2023-01-25  Product2  834.0  North        834

In [ ]:
# Want to multiply each value from 'Sales' by 2:

In [ ]:
df['Sales_new'] = df['Sales'].apply(lambda x:x**2)
df

    Sales Date   Product  Sales Region  Value_new  Sales_new
0   2023-01-01  Product3  738.0   West        738   544644.0
1   2023-01-02  Product2  868.0  North        868   753424.0
2   2023-01-03  Product2  554.0   West        554   306916.0
3   2023-01-04  Product1  618.0  South        618   381924.0
4   2023-01-05  Product3  501.0   East        501   251001.0
5   2023-01-06  Product1  554.0   West        554   306916.0
6   2023-01-07  Product3  339.0  South        339   114921.0
7   2023-01-08  Product3  280.0  South        280    78400.0
8   2023-01-09  Product2  806.0  North        806   649636.0
9   2023-01-10  Product2  816.0  South        816   665856.0
10  2023-01-11  Product3  469.0   West        469   219961.0
11  2023-01-12  Product3  554.0   East        554   306916.0
12  2023-01-13  Product3  554.0   East        554   306916.0
13  2023-01-14  Product3  676.0   East        676   456976.0
14  2023-01-15  Product1  183.0  South        183    33489.0
15  2023-01-16  Product1  424.0  South        424   179776.0
16  2023-01-17  Product1  554.0  South        554   306916.0
17  2023-01-18  Product1  554.0  South        554   306916.0
18  2023-01-19  Product2  124.0  North        124    15376.0
19  2023-01-20  Product3  732.0   West        732   535824.0
20  2023-01-21  Product2  554.0   West        554   306916.0
21  2023-01-22  Product3  296.0   West        296    87616.0
22  2023-01-23  Product2  737.0   West        737   543169.0
23  2023-01-24  Product3  531.0   East        531   281961.0
24  2023-01-25  Product2  834.0  North        834   695556.0

## Data Aggregating And Grouping

In [ ]:
# Group avg. sales value by product:
grouped_mean = df.groupby('Product')['Sales'].mean()

In [ ]:
grouped_mean

Product
Product1    481.166667
Product2    661.625000
Product3    515.454545
Name: Sales, dtype: float64

In [ ]:
# Grouped Sum:
grpuped_sum = df.groupby(['Product', 'Region'])['Sales'].sum()
grpuped_sum

Product   Region
Product1  South     2333.0
          West       554.0
Product2  North     2632.0
          South      816.0
          West      1845.0
Product3  East      2816.0
          South      619.0
          West      2235.0
Name: Sales, dtype: float64

#### Aggregate multiple functions:

In [ ]:
groudped_agg=df.groupby('Product')['Sales'].agg(['mean','sum','count'])
groudped_agg

                mean     sum  count
Product
Product1  481.166667  2887.0      6
Product2  661.625000  5293.0      8
Product3  515.454545  5670.0     11